// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0hNmDb-bP_I73tJoaLXr9WtzuaJsr_D8',
    appId: '1:319652026920:web:1804e57ae03f0878f4731d',
    messagingSenderId: '319652026920',
    projectId: 'walletproject-d9827',
    authDomain: 'walletproject-d9827.firebaseapp.com',
    storageBucket: 'walletproject-d9827.firebasestorage.app',
    measurementId: 'G-TWTBBJ3RGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9jlM4iU_Ed7mm8XRwe21qMQRjBUUl7CY',
    appId: '1:319652026920:android:70fd017a762924f0f4731d',
    messagingSenderId: '319652026920',
    projectId: 'walletproject-d9827',
    storageBucket: 'walletproject-d9827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwWdQLf4kcco-Pxjub0IRQQV_5ItDqfU',
    appId: '1:319652026920:ios:d74eb4f063f01356f4731d',
    messagingSenderId: '319652026920',
    projectId: 'walletproject-d9827',
    storageBucket: 'walletproject-d9827.firebasestorage.app',
    iosBundleId: 'com.example.walletProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwWdQLf4kcco-Pxjub0IRQQV_5ItDqfU',
    appId: '1:319652026920:ios:d74eb4f063f01356f4731d',
    messagingSenderId: '319652026920',
    projectId: 'walletproject-d9827',
    storageBucket: 'walletproject-d9827.firebasestorage.app',
    iosBundleId: 'com.example.walletProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0hNmDb-bP_I73tJoaLXr9WtzuaJsr_D8',
    appId: '1:319652026920:web:b1bca08614eca5f8f4731d',
    messagingSenderId: '319652026920',
    projectId: 'walletproject-d9827',
    authDomain: 'walletproject-d9827.firebaseapp.com',
    storageBucket: 'walletproject-d9827.firebasestorage.app',
    measurementId: 'G-DBXNK78ED2',
  );
}
